### ISSUE TITLE
`decrypt` Only decrypts received messages, not the ones the user has sent

### ISSUE THREAD

**Issue by andyboyd** [bitclout/identity#19]
Not sure if this is a bug, a limitation, or a design decision. When using identity to decrypt DMs, it only seems to decrypt the received DMs, and not the ones that the user has sent to the conversation. 

bitclout.com seems to be storing the sent messages in local storage before they get encrypted, and that's how they're able to be rendered in the conversation.

My gut is telling me this is probably because they get encrypted using the receiving user's public key, and therefore require that user's private key to decrypt, and because the sender doesn't have that private key, they can't be decrypted?

Just wondering if there's anything that can be done about that, or is the only option to cache the unencrypted messages client side before they get sent? This would mean that if the browser storage (or app storage if using a native app) was cleared, those messages would be lost forever to the person who sent them.

**Comment by maebeam** [comment]
> Because the sender doesn't have that private key, they can't be decrypted

This is unfortunately correct
