### ISSUE TITLE
Using 'jwt' method with read-only access

### ISSUE THREAD

**Issue by lobovkin** [bitclout/identity#2]
As I understand it, this method was added to verify from the server side that the token is signed by an authorized user.

But this method requires passing 'encryptedSeedHex' in the payload. And 'encryptedSeedHex' is not available with read-only access (empty string).

I suggest to make this method without the requirement to pass 'encryptedSeedHex'.

**Comment by maebeam** [comment]
`encryptedSeedHex` is required for the user to prove their identity. Soon we will send `encryptedSeedHex` with `ReadOnly` access level and the `jwt` message will work.

**Comment by lobovkin** [comment]
> `encryptedSeedHex` is required for the user to prove their identity. Soon we will send `encryptedSeedHex` with `ReadOnly` access level and the `jwt` message will work.

But does `encryptedSeedHex` give you access to decrypt received private messages? I would not like to get such rights only for user authorization on the server.

It would be great to have a mode for authorization on third-party services without access to private messages, but the ability to get and verify the token. It's not even read-only, it's auth-only.

**Comment by maebeam** [comment]
It only allows you to decrypt private messages if the iframe allows it aka the user has granted permission. We're moving to a more granular permissions model where apps can request what they want (prove identity, decrypt messages, sign transactions, etc)

**Comment by lobovkin** [comment]
The permission `Require approval for all transactions` now also gives `encryptedSeedHex`, so I tried to use `jwt` method for server-side identity prove , but it requires `AccessLevel.ApproveAll`. Why does it require maximum access?

**Comment by maebeam** [comment]
`ApproveAll` is the lowest permission level you can request now. `ReadOnly` is defunct

**Comment by lobovkin** [comment]
Thank you, my mistake was that I didn't pass the current level to the `jwt` method.

But several people have already written that they do not understand what they give the rights to in the authorization window (I ask for the minimum) and are afraid to authorize.
`Require approval for all transactions` for some people, it looks like my app is asking for the approval for all transactions. And some people don't understand what red crosses mean.

Do you plan to make the labels more understandable to users, not developers?

**Comment by maebeam** [comment]
@lobovkin i would love to make the levels more understandable. open to suggestions / PRs for all copy and UI improvements

**Comment by maebeam** [comment]
This original issue is solved. Opening a new issue for making access levels more user friendly.
