### ISSUE TITLE
Problems with accessLevelRequest

### ISSUE THREAD

**Issue by felpsio** [bitclout/identity#20]
Hi :),

I'm trying to use Bitclout Identity on my application and I'm having some problems/concerns about security:

1 - When I try to send `accessLevelRequest` I don't notice any change in the interface or the final access level authorization. I'm opening the following URL: `https://identity.bitclout.com/log-in?accessLevelRequest=2`. 
 - It doesn't show any message that explicit to the user the level of access and after the user authorizes it always return me the access level 4.
 - I also tried using `accessLevelRequest=AprovaAll`. Am I using the wrong URL or this feature isn't complete yet?
 
 2 - When I'm logged on many user accounts at the same time and use the identity window, it returns me access level 4 for all the logged accounts. Even when I'm selecting just one account. Shouldn't return only the requested level access for the only selected account?

**Comment by iPaulPro** [comment]
`localhost` is part of the whitelist for "admin" domains, so it returns all accounts and uses level 4 no matter what you request. Just use your local IP (192.168.x.x) and you'll see the proper behavior.

**Comment by felpsio** [comment]
Thank you very much @iPaulPro :D. Yep, using 127.0.0.1 also worked fine. It solved my problem :)

**Comment by AdonousTech** [comment]
Thanks @iPaulPro !!
