### ISSUE TITLE
Questions about permission expiration

### ISSUE THREAD

**Issue by felpsio** [bitclout/identity#23]
Hi, I have some questions:

When an application uses Bitclout Identity to get user access, it receives some kinds of tokens that can be used to access user info or depending on the access level, makes transactions for the user with/without his permission.

- Does these tokens ever expire? 
- Is it easy for a user to check all the tokens he generated?
- Can a user revoke these tokens at any moment?

**Comment by maebeam** [comment]
In safari the tokens expire after one week. In chrome they never expire.

A list of the sites that have access is stored in local storage. There is no UI for managing or revoking permissions at the moment.

**Comment by felpsio** [comment]
@maebeam , thank you very much :)
