### ISSUE TITLE
Identity sometimes asks for approval when decrypting even with access level 4

### ISSUE THREAD

**Issue by andyboyd** [bitclout/identity#24]
Not sure under what circumstances this happens, but it seems to be related to how long it's been since access was originally granted. But sometimes when sending a `decrypt` message to identity, it's returning `approvalRequired: true`, even though `AccessLevel: Full` was requested and granted. This shouldn't be happening, full access should mean full access, and approval should not be required for anything. 

I'm using this in a native mobile app with URL: `"https://identity.bitclout.com/embed?accessLevelRequest=4&webview=true"` and the decrypt message being sent is:

```
{
  id: <some uuid>,
  service: 'identity',
  method: 'decrypt',
  payload: {
    accessLevel: 4,
    accessLevelHmac: <stored hmac from login>,
    encryptedSeedHex: <stored encrypted hex from login>,
    encryptedHexes: [<array of encrypted hexes>],
  },
}
```

**Comment by andyboyd** [comment]
@maebeam , any input on this? Would be good to know if this behaviour is expected, because it's pretty breaking right now for us.

**Comment by maebeam** [comment]
Sorry I missed this, for some reason my notifications were misconfigured.

Safari expires third party cookies after one week. If the cookie is expired we need the user to visit identity and click a button so we can store the cookie for another week. It sounds like we may need a special case where we use localStorage for Safari first party webviews embedded in apps

**Comment by maebeam** [comment]
Should be as simple as changing this function:

```
  mustUseStorageAccess(): boolean {
    return typeof document.hasStorageAccess === 'function' && !this.globalVars.webview;
  }
```

**Comment by maebeam** [comment]
Give that a try locally and either submit a PR or I can make the change for you

**Comment by andyboyd** [comment]
I can give it a try locally, but if I understand correctly, I'll not be able to know if it's worked for a week? I think I'd prefer if you just made the change if that's ok, we've got actual real life users on our app now, so would be best if the fix got in as quickly as possible, and that'll probably happen faster with you making the changes. 

I imagine after this fix is applied, user's will need to log out and back in to make sure identity stores things in the right place? If so, I'll need to put something into the app to make that happen when it needs to.

**Comment by andyboyd** [comment]
Actually, I was able to verify locally that it works by changing the system time. I'll raise a PR now. Unfortunately it does seem that users will have to log out and back in again to avoid getting stuck, but I don't think that can be helped.

**Comment by andyboyd** [comment]
I think this is probably resolved now, but I'd like to leave it open until I can verify that cookies are no longer expiring and locking users out if that's alright? Should know in a week or so.

**Comment by maebeam** [comment]
Sure, sounds good

**Comment by maebeam** [comment]
Closing since this seems resolved
