### ISSUE TITLE
Associate old accounts with Google Login

### ISSUE THREAD

**Issue by felpsio** [bitclout/identity#33]
Hi :), I would like to confirm a couple of questions about the Google Login:

- Is it possible to associate old Bitclout accounts with the Google Login or only new ones?
- If not, is this feature planed to be launch soon?

**Comment by maebeam** [comment]
Hi! Thanks for your question.

Only new accounts can be linked to Google accounts at the moment. Moving existing accounts to Google will require a much more complicated interface. We would like to build this but we're not sure when it will be done.

**Comment by felpsio** [comment]
@maebeam thank you very much :)
