### ISSUE TITLE
Username and profile pic

### ISSUE THREAD

**Issue by atyazin** [bitclout/identity#38]
I'm trying to add a BitClout login functionality to our web application. 

So far I'm able to use the window.open context and send messages to "https://identity.bitclout.com/". 

I'm getting the JWT and the public key of the user, but I need at least a username and profile picture. 

Is there a way to get them? I saw that you have an endpoint in the backend-api.service, that returns the username and the profilePic (GetUsersStateless) - is there a way to consume this from our webapp?

**Comment by maebeam** [comment]
The CORS policy will prevent you from fetching this at the moment. We recommend running your own `backend` node so you can call `GetUsersStateless`. Alternatively, you can call `GetUsersStateless` from your own backend server and optionally cache the results in your own database.

Closing this but happy to provide more help if need be.
