### ISSUE TITLE
Identity uses browser time, not server time to sign JWTs

### ISSUE THREAD

**Issue by Zyther** [bitclout/identity#43]
Steps to reproduce: 

Use a Windows PC

* Set local time on local PC one minute behind of actual time
* get a token from identity.bitclout.com using a local browser
* Token will already be expired

**Comment by maebeam** [comment]
There's no way to fix this because Identity doesn't have a backend server to talk to and we don't want to add any server-side dependencies.

**Comment by maebeam** [comment]
I'm open to increasing the token time or allowing the requester to specify an expiry time

**Comment by Zyther** [comment]
Understood, and thank you.

**Comment by Zyther** [comment]
After further thought, I feel this strictness is a good thing. Ensures all parties are in agreeance of the current time. Apologies!

**Comment by maebeam** [comment]
I think we should increase the token expiry time to account for clock skew. 10-30 minutes seems reasonable

**Comment by maebeam** [comment]
Increased to 10 minutes: d79b17c
