### ISSUE TITLE
Questions about approved transactions

### ISSUE THREAD

**Issue by felpsio** [bitclout/identity#58]
Hey,

I'm checking the feasibility of signing transactions but only submitting them conditionally. For this use case I have two questions:
- When the user signs a transaction, he receives a `TransactionHex` that can be submitted to confirm the transaction on chain. Does this TransactionHex has any kind of expiration or can be used forever and still work as long the user has the necessary clout to perform the operation?
- Once I received a signed `TransactionHex` from the user, is there a way to check if the code is valid without confirming the transaction?

**Comment by maebeam** [comment]
Hi! The signed transaction consumes and creates UTXOs. If the user creates a second transaction that consumes the same UTXOs and submits it then the first transaction will no longer be valid. There is no endpoint at the moment to check if a transaction is invalid but it most likely will become invalid relatively quickly.

This behavior will change when we moved from UTXOs to Balances, but that is still a few months out.

**Comment by felpsio** [comment]
Tyvm @maebeam :)
